kind: Deployment
apiVersion: apps/v1
metadata:
  name: myapp
spec:
  replicas: 2
  selector:
    matchLabels:
      app: myapp
  template:
    metadata:
      labels:
        app: myapp
    spec:
      containers:
        - name: my-react-app
          image: 496572606827.dkr.ecr.us-east-1.amazonaws.com/wel-my-account-ui:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 80
      restartPolicy: Always