    node {

        // Checking out
        stage("Checkout") {
               sh '''
                    git checkout develop
               '''
        }

         // Merge with target branch in case if this is a PR
        stage('Merge target OR Parse commit message') {
                    sh '''
                       git merge origin/$CHANGE_TARGET
                    '''
        }

        stage('Build Image & Push to Registry') {
            sh '''
                docker-compose build
                docker tag myapp_react-app 496572606827.dkr.ecr.us-east-1.amazonaws.com/my-react-app:v1
                docker push 496572606827.dkr.ecr.us-east-1.amazonaws.com/my-react-app:v1
            '''
        }
    }


